#!/bin/bash

if [ ! -d "busybox-1.33.0" ]; then
    wget https://busybox.net/downloads/busybox-1.33.0.tar.bz2
    tar xjf busybox-1.33.0.tar.bz2
fi

cd busybox-1.33.0/

if [ ! -f "busybox" ]; then
    make defconfig
    make
fi

cd ../

if [ ! -d "rootfs" ]; then
    mkdir rootfs
    cd rootfs
    mkdir -p bin etc proc sys dev
    cp busybox-1.33.0/busybox bin/
fi

