#!/bin/bash

have_ns=`ip netns list | grep my_net_ns | wc -l`

if [ $have_ns -eq 1 ]; then
    echo "FOUND"
else
    ip netns add my_net_ns
fi

ip link add name br0 type bridge
ip link set br0 up

sudo ip netns exec my_net_ns ip link delete veth0
sudo ip netns exec my_net_ns ip link add veth0 type veth peer name veth1

sudo ip link add veth1 type veth peer name veth0
sudo ip link set veth1 master br0
sudo ip link set veth1 up

sudo ip netns exec my_net_ns ip link set veth0 netns 1
sudo ip netns exec my_net_ns ip link set veth0 name eth0
sudo ip netns exec my_net_ns ip link set eth0 up
