name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTUP_TOOLCHAIN: nightly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/setup-rust@v1
        with:
          rust-version: nightly
          profile: minimal
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test it_works --verbose

